imports:
    - { resource: zodiac.yml }
    - { resource: tables.yml }

services:
    ganstaz.zodiac.helper:
        class: ganstaz\zodiac\src\helper
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '%ganstaz.zodiac.table%'
            - '%ganstaz.zodiac.dates_table%'

    ganstaz.gzo.tab.zodiac:
        class: ganstaz\zodiac\src\tabs\type\zodiac
        shared: false
        parent: ganstaz.gzo.tab.base
        arguments:
            - '@config'
            - '@?ganstaz.zodiac.manager'
        calls:
            - [set_name, [zodiac]]
        tags:
            - { name: gzo.tab.type, order: 26 }

    ganstaz.zodiac.listener:
        class: ganstaz\zodiac\src\subscriber\subscribers
        arguments:
            - '@language'
        tags:
            - { name: event.listener }
