imports:
    - { resource: zodiac.yml }
    - { resource: tables.yml }

services:
    ganstaz.zodiac.helper:
        class: ganstaz\zodiac\core\helper
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '%ganstaz.web.tables.zodiac%'
            - '%ganstaz.web.tables.zodiac_dates%'

    ganstaz.zodiac.listener:
        class: ganstaz\zodiac\event\listener
        arguments:
            - '@config'
            - '@language'
            - '@template'
            - '@?ganstaz.zodiac.manager'
        tags:
            - { name: event.listener }
