imports:
    - { resource: zodiac.yml }
    - { resource: tables.yml }

services:
    ganstaz.zodiac.helper:
        class: ganstaz\zodiac\core\helper
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '%ganstaz.web.tables.zodiac%'
            - '%ganstaz.web.tables.zodiac_dates%'
