parameters:
    ganstaz.web.tables.zodiac: '%core.table_prefix%gzo_zodiac'
    ganstaz.web.tables.zodiac_dates: '%core.table_prefix%gzo_zodiac_dates'
    ganstaz.web.tables.zodiac_symbols: '%core.table_prefix%gzo_zodiac_symbols'
    ganstaz.web.tables.heavenly_stems: '%core.table_prefix%gzo_zodiac_heavenly_stems'
