parameters:
    ganstaz.zodiac.table: '%core.table_prefix%gzo_zodiac'
    ganstaz.zodiac.dates_table: '%core.table_prefix%gzo_zodiac_dates'
    ganstaz.zodiac.symbols_table: '%core.table_prefix%gzo_zodiac_symbols'
    ganstaz.zodiac.heavenly_stems_table: '%core.table_prefix%gzo_zodiac_heavenly_stems'
