services:
    ganstaz.zodiac.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: gzo.web.zodiac }

# Zodiac types
    ganstaz.web.zodiac:
        class: ganstaz\zodiac\core\type\zodiac
        arguments:
            - '@ganstaz.zodiac.helper'
        calls:
            - [set_format, [m-d]]
        tags:
            - { name: ganstaz.zodiac.plugin }

    ganstaz.web.zodiac.chinese:
        class: ganstaz\zodiac\core\type\chinese
        arguments:
            - '@dbal.conn'
            - '%ganstaz.web.tables.zodiac_symbols%'
            - '%ganstaz.web.tables.heavenly_stems%'
        calls:
            - [set_format, [Y]]
        tags:
            - { name: ganstaz.zodiac.plugin }

    ganstaz.web.zodiac.myanmar:
        class: ganstaz\zodiac\core\type\myanmar
        arguments:
            - '@ganstaz.zodiac.helper'
        calls:
            - [set_format, [l]]
        tags:
            - { name: ganstaz.zodiac.plugin }
